server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zzimkong?serverTimezone=UTC&characterEncoding=UTF-8
    username: zzimkong
    password: khjjhr0330
    driver-class-name: com.mysql.cj.jdbc.Driver
  graphql:
    graphiql:
      enabled: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
