server:
  port: 8080

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      host: localhost
      port: 27017
      database: zzimkong
      authentication-database: admin
      username: root
      password: P@ssw0rd
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
  graphql:
    graphiql:
      enabled: true
  jpa:
    show-sql: true
