server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/zzimkong?useUnicode=true&characterEncoding=utf8
    username: zzimkong
    password: khjjhr0330
  graphql:
    graphiql:
      enabled: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
