server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/zzimkong?useUnicode=true&characterEncoding=utf8
    username:
    password:
  graphql:
    graphiql:
      enabled: true
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

kafka:
  host: localhost:9092
  topic: zzimkong
  groupId: 1234
