server:
    port: 8082

spring:
    data:
        mongodb:
            host: localhost
            port: 27017
            authentication-database: admin
            username: zzimkong
            password:
            database: zzimkong

    graphql:
        graphiql:
            enabled: true

kafka:
    host: localhost:9092
    topic: zzimkong
    groupId: 1234
